// Class: ReadBDT
// Automatically generated by MethodBase::MakeClass
//

/* configuration options =====================================================

#GEN -*-*-*-*-*-*-*-*-*-*-*- general info -*-*-*-*-*-*-*-*-*-*-*-

Method         : BDT::BDT
TMVA Release   : 4.2.1         [262657]
ROOT Release   : 6.22/08       [398856]
Creator        : root
Date           : Thu Oct 14 12:11:37 2021
Host           : Linux root-ubuntu-2004-2 5.4.0-33-generic #37-Ubuntu SMP Thu May 21 12:53:59 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
Dir            : /work/test
Training events: 33970
Analysis type  : [Classification]


#OPT -*-*-*-*-*-*-*-*-*-*-*-*- options -*-*-*-*-*-*-*-*-*-*-*-*-

# Set by User:
V: "False" [Verbose output (short form of "VerbosityLevel" below - overrides the latter one)]
NTrees: "200" [Number of trees in the forest]
MaxDepth: "2" [Max depth of the decision tree allowed]
MinNodeSize: "2.5%" [Minimum percentage of training events required in a leaf node (default: Classification: 5%, Regression: 0.2%)]
nCuts: "20" [Number of grid points in variable range used in finding optimal cut in node splitting]
BoostType: "AdaBoost" [Boosting type for the trees in the forest (note: AdaCost is still experimental)]
UseBaggedBoost: "True" [Use only a random subsample of all events for growing the trees in each boost iteration.]
AdaBoostBeta: "5.000000e-01" [Learning rate  for AdaBoost algorithm]
BaggedSampleFraction: "5.000000e-01" [Relative size of bagged event sample to original size of the data sample (used whenever bagging is used (i.e. UseBaggedBoost, Bagging,)]
SeparationType: "giniindex" [Separation criterion for node splitting]
# Default:
VerbosityLevel: "Default" [Verbosity level]
VarTransform: "None" [List of variable transformations performed before training, e.g., "D_Background,P_Signal,G,N_AllClasses" for: "Decorrelation, PCA-transformation, Gaussianisation, Normalisation, each for the given class of events ('AllClasses' denotes all events of all classes, if no class indication is given, 'All' is assumed)"]
H: "False" [Print method-specific help message]
CreateMVAPdfs: "False" [Create PDFs for classifier outputs (signal and background)]
IgnoreNegWeightsInTraining: "False" [Events with negative weights are ignored in the training (but are included for testing and performance evaluation)]
AdaBoostR2Loss: "quadratic" [Type of Loss function in AdaBoostR2]
Shrinkage: "1.000000e+00" [Learning rate for BoostType=Grad algorithm]
UseRandomisedTrees: "False" [Determine at each node splitting the cut variable only as the best out of a random subset of variables (like in RandomForests)]
UseNvars: "1" [Size of the subset of variables used with RandomisedTree option]
UsePoissonNvars: "True" [Interpret "UseNvars" not as fixed number but as mean of a Poisson distribution in each split with RandomisedTree option]
UseYesNoLeaf: "True" [Use Sig or Bkg categories, or the purity=S/(S+B) as classification of the leaf node -> Real-AdaBoost]
NegWeightTreatment: "inverseboostnegweights" [How to treat events with negative weights in the BDT training (particular the boosting) : IgnoreInTraining;  Boost With inverse boostweight; Pair events with negative and positive weights in training sample and *annihilate* them (experimental!)]
Css: "1.000000e+00" [AdaCost: cost of true signal selected signal]
Cts_sb: "1.000000e+00" [AdaCost: cost of true signal selected bkg]
Ctb_ss: "1.000000e+00" [AdaCost: cost of true bkg    selected signal]
Cbb: "1.000000e+00" [AdaCost: cost of true bkg    selected bkg ]
NodePurityLimit: "5.000000e-01" [In boosting/pruning, nodes with purity > NodePurityLimit are signal; background otherwise.]
RegressionLossFunctionBDTG: "huber" [Loss function for BDTG regression.]
HuberQuantile: "7.000000e-01" [In the Huber loss function this is the quantile that separates the core from the tails in the residuals distribution.]
DoBoostMonitor: "False" [Create control plot with ROC integral vs tree number]
UseFisherCuts: "False" [Use multivariate splits using the Fisher criterion]
MinLinCorrForFisher: "8.000000e-01" [The minimum linear correlation between two variables demanded for use in Fisher criterion in node splitting]
UseExclusiveVars: "False" [Variables already used in fisher criterion are not anymore analysed individually for node splitting]
DoPreselection: "False" [and and apply automatic pre-selection for 100% efficient signal (bkg) cuts prior to training]
SigToBkgFraction: "1.000000e+00" [Sig to Bkg ratio used in Training (similar to NodePurityLimit, which cannot be used in real adaboost]
PruneMethod: "nopruning" [Note: for BDTs use small trees (e.g.MaxDepth=3) and NoPruning:  Pruning: Method used for pruning (removal) of statistically insignificant branches ]
PruneStrength: "0.000000e+00" [Pruning strength]
PruningValFraction: "5.000000e-01" [Fraction of events to use for optimizing automatic pruning.]
SkipNormalization: "False" [Skip normalization at initialization, to keep expectation value of BDT output according to the fraction of events]
nEventsMin: "0" [deprecated: Use MinNodeSize (in % of training events) instead]
UseBaggedGrad: "False" [deprecated: Use *UseBaggedBoost* instead:  Use only a random subsample of all events for growing the trees in each iteration.]
GradBaggingFraction: "5.000000e-01" [deprecated: Use *BaggedSampleFraction* instead: Defines the fraction of events to be used in each iteration, e.g. when UseBaggedGrad=kTRUE. ]
UseNTrainEvents: "0" [deprecated: Use *BaggedSampleFraction* instead: Number of randomly picked training events used in randomised (and bagged) trees]
NNodesMax: "0" [deprecated: Use MaxDepth instead to limit the tree size]
##


#VAR -*-*-*-*-*-*-*-*-*-*-*-* variables *-*-*-*-*-*-*-*-*-*-*-*-

NVar 1
B_Eta                         B_Eta                         B_Eta                         B_Eta                                                           'F'    [-2.42993068695,2.49441289902]
NSpec 0


============================================================================ */

#include <array>
#include <vector>
#include <cmath>
#include <string>
#include <iostream>

#include <algorithm>
#include <limits>

#define NN new BDTNode

#ifndef BDTNode__def
#define BDTNode__def

class BDTNode {

public:

   // constructor of an essentially "empty" node floating in space
   BDTNode ( BDTNode* left,BDTNode* right,
                          int selector, double cutValue, bool cutType, 
                          int nodeType, double purity, double response ) :
   fLeft         ( left         ),
   fRight        ( right        ),
   fSelector     ( selector     ),
   fCutValue     ( cutValue     ),
   fCutType      ( cutType      ),
   fNodeType     ( nodeType     ),
   fPurity       ( purity       ),
   fResponse     ( response     ){
   }

   virtual ~BDTNode();

   // test event if it descends the tree at this node to the right
   virtual bool GoesRight( const std::vector<double>& inputValues ) const;
   BDTNode* GetRight( void )  {return fRight; };

   // test event if it descends the tree at this node to the left 
   virtual bool GoesLeft ( const std::vector<double>& inputValues ) const;
   BDTNode* GetLeft( void ) { return fLeft; };   

   // return  S/(S+B) (purity) at this node (from  training)

   double GetPurity( void ) const { return fPurity; } 
   // return the node type
   int    GetNodeType( void ) const { return fNodeType; }
   double GetResponse(void) const {return fResponse;}

private:

   BDTNode*   fLeft;     // pointer to the left daughter node
   BDTNode*   fRight;    // pointer to the right daughter node
   int                     fSelector; // index of variable used in node selection (decision tree)   
   double                  fCutValue; // cut value applied on this node to discriminate bkg against sig
   bool                    fCutType;  // true: if event variable > cutValue ==> signal , false otherwise
   int                     fNodeType; // Type of node: -1 == Bkg-leaf, 1 == Signal-leaf, 0 = internal 
   double                  fPurity;   // Purity of node from training
   double                  fResponse; // Regression response value of node
}; 

//_______________________________________________________________________
   BDTNode::~BDTNode()
{
   if (fLeft  != NULL) delete fLeft;
   if (fRight != NULL) delete fRight;
}; 

//_______________________________________________________________________
bool BDTNode::GoesRight( const std::vector<double>& inputValues ) const
{
   // test event if it descends the tree at this node to the right
   bool result;
     result = (inputValues[fSelector] >= fCutValue );
   if (fCutType == true) return result; //the cuts are selecting Signal ;
   else return !result;
}

//_______________________________________________________________________
bool BDTNode::GoesLeft( const std::vector<double>& inputValues ) const
{
   // test event if it descends the tree at this node to the left
   if (!this->GoesRight(inputValues)) return true;
   else return false;
}

#endif

#ifndef IClassifierReader__def
#define IClassifierReader__def

class IClassifierReader {

 public:

   // constructor
   IClassifierReader() : fStatusIsClean( true ) {}
   virtual ~IClassifierReader() {}

   // return classifier response
   virtual double GetMvaValue( const std::vector<double>& inputValues ) const = 0;

   // returns classifier status
   bool IsStatusClean() const { return fStatusIsClean; }

 protected:

   bool fStatusIsClean;
};

#endif

class ReadBDT : public IClassifierReader {

 public:

   // constructor
   ReadBDT( std::vector<std::string>& theInputVars )
      : IClassifierReader(),
        fClassName( "ReadBDT" ),
        fNvars( 1 )
   {
      // the training input variables
      const char* inputVars[] = { "B_Eta" };

      // sanity checks
      if (theInputVars.size() <= 0) {
         std::cout << "Problem in class \"" << fClassName << "\": empty input vector" << std::endl;
         fStatusIsClean = false;
      }

      if (theInputVars.size() != fNvars) {
         std::cout << "Problem in class \"" << fClassName << "\": mismatch in number of input values: "
                   << theInputVars.size() << " != " << fNvars << std::endl;
         fStatusIsClean = false;
      }

      // validate input variables
      for (size_t ivar = 0; ivar < theInputVars.size(); ivar++) {
         if (theInputVars[ivar] != inputVars[ivar]) {
            std::cout << "Problem in class \"" << fClassName << "\": mismatch in input variable names" << std::endl
                      << " for variable [" << ivar << "]: " << theInputVars[ivar].c_str() << " != " << inputVars[ivar] << std::endl;
            fStatusIsClean = false;
         }
      }

      // initialize min and max vectors (for normalisation)
      fVmin[0] = 0;
      fVmax[0] = 0;

      // initialize input variable types
      fType[0] = 'F';

      // initialize constants
      Initialize();

   }

   // destructor
   virtual ~ReadBDT() {
      Clear(); // method-specific
   }

   // the classifier response
   // "inputValues" is a vector of input values in the same order as the
   // variables given to the constructor
   double GetMvaValue( const std::vector<double>& inputValues ) const override;

 private:

   // method-specific destructor
   void Clear();

   // common member variables
   const char* fClassName;

   const size_t fNvars;
   size_t GetNvar()           const { return fNvars; }
   char   GetType( int ivar ) const { return fType[ivar]; }

   // normalisation of input variables
   double fVmin[1];
   double fVmax[1];
   double NormVariable( double x, double xmin, double xmax ) const {
      // normalise to output range: [-1, 1]
      return 2*(x - xmin)/(xmax - xmin) - 1.0;
   }

   // type of input variable: 'F' or 'I'
   char   fType[1];

   // initialize internal variables
   void Initialize();
   double GetMvaValue__( const std::vector<double>& inputValues ) const;

   // private members (method specific)
   std::vector<BDTNode*> fForest;       // i.e. root nodes of decision trees
   std::vector<double>                fBoostWeights; // the weights applied in the individual boosts
};

double ReadBDT::GetMvaValue__( const std::vector<double>& inputValues ) const
{
   double myMVA = 0;
   double norm  = 0;
   for (unsigned int itree=0; itree<fForest.size(); itree++){
      BDTNode *current = fForest[itree];
      while (current->GetNodeType() == 0) { //intermediate node
         if (current->GoesRight(inputValues)) current=(BDTNode*)current->GetRight();
         else current=(BDTNode*)current->GetLeft();
      }
      myMVA += fBoostWeights[itree] *  current->GetNodeType();
      norm  += fBoostWeights[itree];
   }
   return myMVA /= norm;
}

void ReadBDT::Initialize()
{
  double inf = std::numeric_limits<double>::infinity();
  double nan = std::numeric_limits<double>::quiet_NaN();
  // itree = 0
  fBoostWeights.push_back(0.339995598963671);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 1,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.637888,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.378758,-99) , 
0, -0.0656718, 1, 0, 0.445459,-99) , 
0, -1.28594, 1, 0, 0.502042,-99)    );
  // itree = 1
  fBoostWeights.push_back(0.26089);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 1,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.601487,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.417787,-99) , 
0, -0.0481596, 1, 0, 0.465171,-99) , 
0, -1.27178, 1, 0, 0.517484,-99)    );
  // itree = 2
  fBoostWeights.push_back(0.159132);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 1,-99) , 
NN(
0, 
0, 
-1, 1.88365, 1, -1, 0.464055,-99) , 
0, -1.27746, 1, 0, 0.513666,-99)    );
  // itree = 3
  fBoostWeights.push_back(0.14304);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 1,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.503944,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.303152,-99) , 
0, 1.88484, 1, 0, 0.476228,-99) , 
0, -1.26893, 1, 0, 0.521378,-99)    );
  // itree = 4
  fBoostWeights.push_back(0.151317);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 1,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.846954,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.480036,-99) , 
0, 1.95967, 0, 0, 0.494586,-99) , 
0, -1.24895, 1, 0, 0.540202,-99)    );
  // itree = 5
  fBoostWeights.push_back(0.144298);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 1,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.83481,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.481965,-99) , 
0, 1.95846, 0, 0, 0.495379,-99) , 
0, -1.25747, 1, 0, 0.540022,-99)    );
  // itree = 6
  fBoostWeights.push_back(0.216811);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 1,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.557904,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.379812,-99) , 
0, 1.78339, 1, 0, 0.52906,-99) , 
0, -1.23887, 1, 0, 0.571299,-99)    );
  // itree = 7
  fBoostWeights.push_back(0.161356);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 1,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.651096,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.489114,-99) , 
0, 1.35937, 0, 0, 0.52512,-99) , 
0, -1.26893, 1, 0, 0.564455,-99)    );
  // itree = 8
  fBoostWeights.push_back(0.156717);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 1,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.525334,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.338566,-99) , 
0, 1.87422, 1, 0, 0.500083,-99) , 
0, -1.27178, 1, 0, 0.537323,-99)    );
  // itree = 9
  fBoostWeights.push_back(0.12909);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 1,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.507394,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.238454,-99) , 
0, -1.07861, 0, 0, 0.484509,-99) , 
0, -1.25747, 1, 0, 0.523001,-99)    );
  // itree = 10
  fBoostWeights.push_back(0.175546);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 1,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.64671,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.469989,-99) , 
0, 1.3499, 0, 0, 0.507239,-99) , 
0, -1.27178, 1, 0, 0.542944,-99)    );
  // itree = 11
  fBoostWeights.push_back(0.162455);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 1,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.534707,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.275458,-99) , 
0, -1.10219, 0, 0, 0.514778,-99) , 
0, -1.2803, 1, 0, 0.54839,-99)    );
  // itree = 12
  fBoostWeights.push_back(0.220228);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 1,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.627731,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.434604,-99) , 
0, -0.0417283, 1, 0, 0.481395,-99) , 
0, -1.26893, 1, 0, 0.515848,-99)    );
  // itree = 13
  fBoostWeights.push_back(0.14118);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 1,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.522611,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.342256,-99) , 
0, 1.88628, 1, 0, 0.498245,-99) , 
0, -1.25885, 1, 0, 0.530218,-99)    );
  // itree = 14
  fBoostWeights.push_back(0.185135);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 1,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.561101,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.431803,-99) , 
0, 0.476088, 0, 0, 0.49245,-99) , 
0, -1.27178, 1, 0, 0.523542,-99)    );
  // itree = 15
  fBoostWeights.push_back(0.141795);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 1,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.514887,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.299595,-99) , 
0, 1.87308, 1, 0, 0.481757,-99) , 
0, -1.2803, 1, 0, 0.512394,-99)    );
  // itree = 16
  fBoostWeights.push_back(0.145579);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 1,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.908382,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.469643,-99) , 
0, 1.95846, 0, 0, 0.485437,-99) , 
0, -1.25747, 1, 0, 0.517386,-99)    );
  // itree = 17
  fBoostWeights.push_back(0.131313);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 1,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.597126,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.479755,-99) , 
0, -0.0656718, 1, 0, 0.510115,-99) , 
0, -1.28594, 1, 0, 0.536906,-99)    );
  // itree = 18
  fBoostWeights.push_back(0.201332);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 1,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.639918,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.441828,-99) , 
0, 1.24668, 0, 0, 0.484708,-99) , 
0, -1.24895, 1, 0, 0.51321,-99)    );
  // itree = 19
  fBoostWeights.push_back(0.141532);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 1,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.528609,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.331734,-99) , 
0, 1.88484, 1, 0, 0.501881,-99) , 
0, -1.26893, 1, 0, 0.526904,-99)    );
  // itree = 20
  fBoostWeights.push_back(0.172048);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 1,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.563192,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.438066,-99) , 
0, 0.987473, 1, 0, 0.510844,-99) , 
0, -1.26734, 1, 0, 0.536031,-99)    );
  // itree = 21
  fBoostWeights.push_back(0.11093);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 1,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.515174,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.357925,-99) , 
0, 1.88367, 1, 0, 0.493497,-99) , 
0, -1.27746, 1, 0, 0.517961,-99)    );
  // itree = 22
  fBoostWeights.push_back(0.163816);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 1,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.649399,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.461241,-99) , 
0, 1.34987, 0, 0, 0.498018,-99) , 
0, -1.27178, 1, 0, 0.521767,-99)    );
  // itree = 23
  fBoostWeights.push_back(0.149774);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 1,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.551287,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.442772,-99) , 
0, 0.453218, 0, 0, 0.495099,-99) , 
0, -1.28082, 1, 0, 0.517723,-99)    );
  // itree = 24
  fBoostWeights.push_back(0.0910797);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 1,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.844271,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.489477,-99) , 
0, 1.95846, 0, 0, 0.503266,-99) , 
0, -1.25747, 1, 0, 0.526118,-99)    );
  // itree = 25
  fBoostWeights.push_back(0.118255);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 1,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.6138,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.478472,-99) , 
0, 1.32003, 0, 0, 0.505359,-99) , 
0, -1.28115, 1, 0, 0.525775,-99)    );
  // itree = 26
  fBoostWeights.push_back(0.114666);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 1,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.525293,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.311217,-99) , 
0, -1.09698, 0, 0, 0.509496,-99) , 
0, -1.27178, 1, 0, 0.53041,-99)    );
  // itree = 27
  fBoostWeights.push_back(0.209286);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 1.28492, 0, 1, 0.58768,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.300299,-99) , 
0, 1.90431, 1, 0, 0.548017,-99)    );
  // itree = 28
  fBoostWeights.push_back(0.141286);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 1,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.866622,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.460234,-99) , 
0, 1.9597, 0, 0, 0.474936,-99) , 
0, -1.24895, 1, 0, 0.496699,-99)    );
  // itree = 29
  fBoostWeights.push_back(0.171392);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 1,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.611553,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.456333,-99) , 
0, 0.308409, 1, 0, 0.512979,-99) , 
0, -1.26893, 1, 0, 0.531515,-99)    );
  // itree = 30
  fBoostWeights.push_back(0.14063);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 1,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.552171,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.443574,-99) , 
0, 1.00909, 1, 0, 0.509052,-99) , 
0, -1.26893, 1, 0, 0.526653,-99)    );
  // itree = 31
  fBoostWeights.push_back(0.078051);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 1,-99) , 
NN(
0, 
0, 
-1, 1.88484, 1, -1, 0.476949,-99) , 
0, -1.26893, 1, 0, 0.49438,-99)    );
  // itree = 32
  fBoostWeights.push_back(0.124498);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 1,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.655616,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.480431,-99) , 
0, 1.34992, 0, 0, 0.514617,-99) , 
0, -1.27178, 1, 0, 0.531526,-99)    );
  // itree = 33
  fBoostWeights.push_back(0.164549);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 1,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.593556,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.455921,-99) , 
0, 0.476088, 0, 0, 0.520205,-99) , 
0, -1.27178, 1, 0, 0.536115,-99)    );
  // itree = 34
  fBoostWeights.push_back(0.131979);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 1,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.532698,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.262019,-99) , 
0, -1.10162, 0, 0, 0.508098,-99) , 
0, -1.27746, 1, 0, 0.523727,-99)    );
  // itree = 35
  fBoostWeights.push_back(0.166996);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 1,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.556485,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.411836,-99) , 
0, 1.06525, 1, 0, 0.501408,-99) , 
0, -1.25747, 1, 0, 0.517799,-99)    );
  // itree = 36
  fBoostWeights.push_back(0.110374);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 1,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.529366,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.327593,-99) , 
0, -1.08615, 0, 0, 0.513521,-99) , 
0, -1.2617, 1, 0, 0.528733,-99)    );
  // itree = 37
  fBoostWeights.push_back(0.132127);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 1,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.555355,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.450673,-99) , 
0, 0.475991, 0, 0, 0.499515,-99) , 
0, -1.27178, 1, 0, 0.514648,-99)    );
  // itree = 38
  fBoostWeights.push_back(0.123649);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 1,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.848615,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.462337,-99) , 
0, 1.95967, 0, 0, 0.475588,-99) , 
0, -1.24895, 1, 0, 0.490893,-99)    );
  // itree = 39
  fBoostWeights.push_back(0.185474);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 1.28616, 0, 1, 0.580883,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.334742,-99) , 
0, 1.90412, 1, 0, 0.549361,-99)    );
  // itree = 40
  fBoostWeights.push_back(0.161493);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 1,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.634607,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.450365,-99) , 
0, 1.24668, 0, 0, 0.488197,-99) , 
0, -1.24895, 1, 0, 0.503528,-99)    );
  // itree = 41
  fBoostWeights.push_back(0.123665);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 1,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.495576,-99) , 
0, 1.2848, 0, 0, 0.539344,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.336415,-99) , 
0, 1.90431, 1, 0, 0.51472,-99)    );
  // itree = 42
  fBoostWeights.push_back(0.249795);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0.41747, 0, 1, 0.602633,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.557992,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.222321,-99) , 
0, 1.28933, 0, 0, 0.408384,-99) , 
0, 1.08746, 1, 0, 0.530693,-99)    );
  // itree = 43
  fBoostWeights.push_back(0.0764163);
  fForest.push_back( 
NN(
0, 
0, 
-1, -1.25747, 1, 1, 0.538134,-99)    );
  // itree = 44
  fBoostWeights.push_back(0.147444);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 1.3263, 0, 1, 0.556222,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.298241,-99) , 
0, 1.95054, 1, 0, 0.52614,-99)    );
  // itree = 45
  fBoostWeights.push_back(0.155815);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 1,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.604962,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.447882,-99) , 
0, -0.000740846, 1, 0, 0.488081,-99) , 
0, -1.24895, 1, 0, 0.501801,-99)    );
  // itree = 46
  fBoostWeights.push_back(0.131954);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 1.3169, 0, 1, 0.545058,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.295418,-99) , 
0, 1.93973, 1, 0, 0.512917,-99)    );
  // itree = 47
  fBoostWeights.push_back(0.161426);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 1,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.866762,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.44309,-99) , 
0, 1.9597, 0, 0, 0.460262,-99) , 
0, -1.24895, 1, 0, 0.473488,-99)    );
  // itree = 48
  fBoostWeights.push_back(0.173893);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 1.28639, 0, 1, 0.548187,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 1,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.198099,-99) , 
0, 2.01396, 0, 0, 0.363214,-99) , 
0, 1.90538, 1, 0, 0.524386,-99)    );
  // itree = 49
  fBoostWeights.push_back(0.308833);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 1,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.407137,-99) , 
0, 1.91771, 1, 0, 0.664391,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.710309,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.393155,-99) , 
0, -0.666657, 1, 0, 0.443437,-99) , 
0, 1.26065, 0, 0, 0.483373,-99)    );
  // itree = 50
  fBoostWeights.push_back(0.27206);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 1,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.443452,-99) , 
0, 1.0907, 1, 0, 0.579827,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.540466,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.203866,-99) , 
0, 0.254609, 1, 0, 0.455241,-99) , 
0, 0.388774, 0, 0, 0.512479,-99)    );
  // itree = 51
  fBoostWeights.push_back(0.291503);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 1,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.475934,-99) , 
0, 1.08832, 1, 0, 0.605698,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.581228,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.298305,-99) , 
0, -0.0191557, 1, 0, 0.439377,-99) , 
0, 0.38398, 0, 0, 0.516434,-99)    );
  // itree = 52
  fBoostWeights.push_back(0.181925);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, -0.0341391, 1, 1, 0.54697,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 1,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.297516,-99) , 
0, -1.20512, 1, 0, 0.37581,-99) , 
0, -0.598063, 0, 0, 0.507959,-99)    );
  // itree = 53
  fBoostWeights.push_back(0.157408);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 1,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.477659,-99) , 
0, 1.31418, 0, 0, 0.523807,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.335211,-99) , 
0, 1.93866, 1, 0, 0.498374,-99)    );
  // itree = 54
  fBoostWeights.push_back(0.121537);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 1,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.536131,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.365828,-99) , 
0, 1.81253, 1, 0, 0.517153,-99) , 
0, 2.02543, 0, 0, 0.531453,-99)    );
  // itree = 55
  fBoostWeights.push_back(0.231513);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, -0.0367816, 1, 1, 0.574641,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.648672,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.157827,-99) , 
0, -0.774024, 1, 0, 0.402688,-99) , 
0, -0.59988, 0, 0, 0.535333,-99)    );
  // itree = 56
  fBoostWeights.push_back(0.109371);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 1,-99) , 
NN(
0, 
0, 
-1, -1.14869, 0, -1, 0.457028,-99) , 
0, 2.02649, 0, 0, 0.470686,-99)    );
  // itree = 57
  fBoostWeights.push_back(0.193992);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 1,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.420193,-99) , 
0, 1.91771, 1, 0, 0.661091,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.514207,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.265447,-99) , 
0, 1.08543, 1, 0, 0.465365,-99) , 
0, 1.26065, 0, 0, 0.503459,-99)    );
  // itree = 58
  fBoostWeights.push_back(0.140132);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, -0.0349745, 1, 1, 0.549755,-99) , 
NN(
0, 
0, 
-1, -0.773601, 1, -1, 0.365855,-99) , 
0, -0.59859, 0, 0, 0.506485,-99)    );
  // itree = 59
  fBoostWeights.push_back(0.0767693);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 1,-99) , 
NN(
0, 
0, 
-1, 1.81478, 1, -1, 0.47587,-99) , 
0, 2.02649, 0, 0, 0.491488,-99)    );
  // itree = 60
  fBoostWeights.push_back(0.177306);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 1,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.448351,-99) , 
0, 1.91771, 1, 0, 0.660896,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 1,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.463141,-99) , 
0, -1.19228, 1, 0, 0.481462,-99) , 
0, 1.26065, 0, 0, 0.518107,-99)    );
  // itree = 61
  fBoostWeights.push_back(0.194875);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 1,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.470103,-99) , 
0, 1.93934, 1, 0, 0.686785,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.517388,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.253824,-99) , 
0, 1.0561, 1, 0, 0.461531,-99) , 
0, 1.23085, 0, 0, 0.505278,-99)    );
  // itree = 62
  fBoostWeights.push_back(0.154484);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 1.91707, 1, 1, 0.700033,-99) , 
NN(
0, 
0, 
-1, 1.08111, 1, -1, 0.452418,-99) , 
0, 1.25799, 0, 0, 0.499604,-99)    );
  // itree = 63
  fBoostWeights.push_back(0.14912);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 1.0601, 1, 1, 0.592755,-99) , 
NN(
0, 
0, 
-1, 0.257992, 1, -1, 0.439393,-99) , 
0, 0.539864, 0, 0, 0.503342,-99)    );
  // itree = 64
  fBoostWeights.push_back(0.193722);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 1,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.448635,-99) , 
0, 1.91685, 1, 0, 0.633989,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.534496,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.286476,-99) , 
0, 1.08047, 1, 0, 0.484359,-99) , 
0, 1.25799, 0, 0, 0.512784,-99)    );
  // itree = 65
  fBoostWeights.push_back(0.0786984);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 1,-99) , 
NN(
0, 
0, 
-1, -1.14869, 0, -1, 0.474128,-99) , 
0, 2.02649, 0, 0, 0.488986,-99)    );
  // itree = 66
  fBoostWeights.push_back(0.184814);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 1,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.487236,-99) , 
0, 1.0907, 1, 0, 0.602169,-99) , 
NN(
0, 
0, 
-1, 0.25401, 1, -1, 0.433158,-99) , 
0, 0.388774, 0, 0, 0.508346,-99)    );
  // itree = 67
  fBoostWeights.push_back(0.207003);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 1.09111, 1, 1, 0.640182,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.526183,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.290735,-99) , 
0, 0.254624, 1, 0, 0.468737,-99) , 
0, 0.388774, 0, 0, 0.545881,-99)    );
  // itree = 68
  fBoostWeights.push_back(0.101476);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 1,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.626804,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.47583,-99) , 
0, -0.725337, 1, 0, 0.495568,-99) , 
0, 2.02649, 0, 0, 0.509724,-99)    );
  // itree = 69
  fBoostWeights.push_back(0.144627);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 1,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.492262,-99) , 
0, 1.90847, 1, 0, 0.669207,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 1,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.467409,-99) , 
0, -1.18557, 1, 0, 0.484353,-99) , 
0, 1.2547, 0, 0, 0.518501,-99)    );
  // itree = 70
  fBoostWeights.push_back(0.18175);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 1.05794, 1, 1, 0.603051,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.564513,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.404631,-99) , 
0, -0.0293214, 1, 0, 0.482519,-99) , 
0, 0.535603, 0, 0, 0.533197,-99)    );
  // itree = 71
  fBoostWeights.push_back(0.162847);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, -0.0344053, 1, 1, 0.561364,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.552454,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.222985,-99) , 
0, -0.771531, 1, 0, 0.413611,-99) , 
0, -0.598063, 0, 0, 0.528017,-99)    );
  // itree = 72
  fBoostWeights.push_back(0.14331);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, -0.0321715, 1, 1, 0.547551,-99) , 
NN(
0, 
0, 
-1, -0.687993, 1, -1, 0.357972,-99) , 
0, -0.599543, 0, 0, 0.50016,-99)    );
  // itree = 73
  fBoostWeights.push_back(0.14709);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 1,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.483054,-99) , 
0, -0.0154561, 1, 0, 0.52444,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.527122,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.232662,-99) , 
0, -0.759243, 1, 0, 0.403613,-99) , 
0, -0.583598, 0, 0, 0.495345,-99)    );
  // itree = 74
  fBoostWeights.push_back(0.0992459);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 1,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.515739,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.288513,-99) , 
0, -1.15719, 0, 0, 0.492528,-99) , 
0, 2.02543, 0, 0, 0.507531,-99)    );
  // itree = 75
  fBoostWeights.push_back(0.0605264);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 1,-99) , 
NN(
0, 
0, 
-1, 1.81253, 1, -1, 0.482952,-99) , 
0, 2.02543, 0, 0, 0.497061,-99)    );
  // itree = 76
  fBoostWeights.push_back(0.160813);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 1,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.497428,-99) , 
0, 1.90617, 1, 0, 0.664179,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.535991,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.345094,-99) , 
0, 1.07325, 1, 0, 0.497944,-99) , 
0, 1.24889, 0, 0, 0.528793,-99)    );
  // itree = 77
  fBoostWeights.push_back(0.195692);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 1,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.481787,-99) , 
0, 1.09461, 1, 0, 0.587669,-99) , 
NN(
0, 
0, 
-1, 0.260925, 1, -1, 0.418357,-99) , 
0, 0.394443, 0, 0, 0.49077,-99)    );
  // itree = 78
  fBoostWeights.push_back(0.165128);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 1,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.481963,-99) , 
0, 1.91993, 1, 0, 0.642224,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 1,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.45115,-99) , 
0, -1.18261, 1, 0, 0.467603,-99) , 
0, 1.2638, 0, 0, 0.500017,-99)    );
  // itree = 79
  fBoostWeights.push_back(0.168018);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 1,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.563123,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.369245,-99) , 
0, -1.15719, 0, 0, 0.545341,-99) , 
0, 2.02543, 0, 0, 0.560017,-99)    );
  // itree = 80
  fBoostWeights.push_back(0.186469);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 1.93933, 1, 1, 0.702068,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.532454,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.306406,-99) , 
0, 1.0561, 1, 0, 0.484589,-99) , 
0, 1.23085, 0, 0, 0.525668,-99)    );
  // itree = 81
  fBoostWeights.push_back(0.16917);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 1.91685, 1, 1, 0.65938,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.583513,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.438147,-99) , 
0, 0.378157, 0, 0, 0.481698,-99) , 
0, 1.25799, 0, 0, 0.511842,-99)    );
  // itree = 82
  fBoostWeights.push_back(0.105308);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 1,-99) , 
NN(
0, 
0, 
-1, -0.520821, 0, -1, 0.459006,-99) , 
0, 2.02543, 0, 0, 0.47252,-99)    );
  // itree = 83
  fBoostWeights.push_back(0.196886);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, -0.532212, 0, 1, 0.635789,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.555532,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.221799,-99) , 
0, 0.0384127, 0, 0, 0.513301,-99) , 
0, -0.0850052, 1, 0, 0.545008,-99)    );
  // itree = 84
  fBoostWeights.push_back(0.23323);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 1,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.494711,-99) , 
0, 0.0466865, 0, 0, 0.567658,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.577844,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.190076,-99) , 
0, 0.405651, 0, 0, 0.471007,-99) , 
0, 0.307485, 1, 0, 0.511464,-99)    );
  // itree = 85
  fBoostWeights.push_back(0.185388);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0.058901, 0, 1, 0.586701,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.531003,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.202836,-99) , 
0, 0.41914, 0, 0, 0.451595,-99) , 
0, 0.320445, 1, 0, 0.509949,-99)    );
  // itree = 86
  fBoostWeights.push_back(0.231401);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 1,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.46375,-99) , 
0, 0.421219, 0, 0, 0.519419,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.839003,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.356057,-99) , 
0, 1.95968, 0, 0, 0.412708,-99) , 
0, 1.09065, 1, 0, 0.481507,-99)    );
  // itree = 87
  fBoostWeights.push_back(0.185069);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 1,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.492502,-99) , 
0, 0.41747, 0, 0, 0.541406,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.888495,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.371381,-99) , 
0, 1.95845, 0, 0, 0.427401,-99) , 
0, 1.08746, 1, 0, 0.500496,-99)    );
  // itree = 88
  fBoostWeights.push_back(0.204218);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0.421999, 0, 1, 0.568855,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.872695,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.372687,-99) , 
0, 1.95968, 0, 0, 0.42989,-99) , 
0, 1.09065, 1, 0, 0.517692,-99)    );
  // itree = 89
  fBoostWeights.push_back(0.168952);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 1,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.436143,-99) , 
0, 1.93756, 1, 0, 0.637938,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.540138,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.307595,-99) , 
0, -1.17103, 0, 0, 0.512007,-99) , 
0, 1.32461, 0, 0, 0.531611,-99)    );
  // itree = 90
  fBoostWeights.push_back(0.166474);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 1,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.425516,-99) , 
0, 1.91771, 1, 0, 0.607021,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 1,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.458343,-99) , 
0, -1.19228, 1, 0, 0.477123,-99) , 
0, 1.26065, 0, 0, 0.498515,-99)    );
  // itree = 91
  fBoostWeights.push_back(0.189802);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 1.0907, 1, 1, 0.585111,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.667906,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.421414,-99) , 
0, -0.681454, 1, 0, 0.479139,-99) , 
0, 0.388774, 0, 0, 0.521299,-99)    );
  // itree = 92
  fBoostWeights.push_back(0.253777);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0.41747, 0, 1, 0.612757,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.862086,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.384946,-99) , 
0, 1.95849, 0, 0, 0.439391,-99) , 
0, 1.08746, 1, 0, 0.547493,-99)    );
  // itree = 93
  fBoostWeights.push_back(0.11086);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 1.3263, 0, 1, 0.54579,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.374874,-99) , 
0, 1.95054, 1, 0, 0.525509,-99)    );
  // itree = 94
  fBoostWeights.push_back(0.197304);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0.0779724, 0, 1, 0.600219,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.550193,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.232611,-99) , 
0, 0.439967, 0, 0, 0.484631,-99) , 
0, 0.340803, 1, 0, 0.537234,-99)    );
  // itree = 95
  fBoostWeights.push_back(0.227645);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 1,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.486061,-99) , 
0, 1.08787, 1, 0, 0.563737,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.591373,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.338787,-99) , 
0, -0.0186748, 1, 0, 0.45768,-99) , 
0, 0.38398, 0, 0, 0.500277,-99)    );
  // itree = 96
  fBoostWeights.push_back(0.211388);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 1,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.408421,-99) , 
0, 1.93685, 1, 0, 0.590705,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.6065,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.423116,-99) , 
0, -0.643541, 1, 0, 0.45353,-99) , 
0, 1.32195, 0, 0, 0.476136,-99)    );
  // itree = 97
  fBoostWeights.push_back(0.161126);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, -0.112378, 1, 1, 0.551576,-99) , 
NN(
0, 
0, 
-1, -1.17106, 0, -1, 0.344118,-99) , 
0, -0.547066, 0, 0, 0.495296,-99)    );
  // itree = 98
  fBoostWeights.push_back(0.139263);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 1,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.478508,-99) , 
0, -0.112378, 1, 0, 0.509199,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.513772,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.228297,-99) , 
0, -1.17106, 0, 0, 0.388993,-99) , 
0, -0.547066, 0, 0, 0.478652,-99)    );
  // itree = 99
  fBoostWeights.push_back(0.172819);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 1,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.460459,-99) , 
0, 1.94048, 1, 0, 0.664589,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.523169,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.325812,-99) , 
0, 1.05846, 1, 0, 0.476884,-99) , 
0, 1.23351, 0, 0, 0.509513,-99)    );
  // itree = 100
  fBoostWeights.push_back(0.111932);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 1,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.525813,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.294272,-99) , 
0, -1.15724, 0, 0, 0.503097,-99) , 
0, 2.02543, 0, 0, 0.516451,-99)    );
  // itree = 101
  fBoostWeights.push_back(0.162935);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 1,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.474329,-99) , 
0, 1.94048, 1, 0, 0.677597,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.515799,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.393564,-99) , 
0, 0.363019, 1, 0, 0.465422,-99) , 
0, 1.23351, 0, 0, 0.502978,-99)    );
  // itree = 102
  fBoostWeights.push_back(0.160933);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 1.09083, 1, 1, 0.579598,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.522814,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.288454,-99) , 
0, 0.254624, 1, 0, 0.451913,-99) , 
0, 0.388774, 0, 0, 0.505924,-99)    );
  // itree = 103
  fBoostWeights.push_back(0.196337);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 1,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.482332,-99) , 
0, -0.00942618, 1, 0, 0.518674,-99) , 
NN(
0, 
0, 
-1, -0.754276, 1, -1, 0.285323,-99) , 
0, -0.579047, 0, 0, 0.453744,-99)    );
  // itree = 104
  fBoostWeights.push_back(0.149378);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, -0.0271181, 1, 1, 0.546573,-99) , 
NN(
0, 
0, 
-1, -0.766918, 1, -1, 0.342514,-99) , 
0, -0.592618, 0, 0, 0.495859,-99)    );
  // itree = 105
  fBoostWeights.push_back(0.166055);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 1.906, 1, 1, 0.664175,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.534643,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.421554,-99) , 
0, 0.372707, 0, 0, 0.454987,-99) , 
0, 1.24889, 0, 0, 0.49055,-99)    );
  // itree = 106
  fBoostWeights.push_back(0.15649);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 1,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.487899,-99) , 
0, 1.91713, 1, 0, 0.637633,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.665217,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.45769,-99) , 
0, -0.674474, 1, 0, 0.491116,-99) , 
0, 1.25799, 0, 0, 0.515637,-99)    );
  // itree = 107
  fBoostWeights.push_back(0.233413);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, -0.00942618, 1, 1, 0.574066,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 1,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.303364,-99) , 
0, -1.19229, 1, 0, 0.371544,-99) , 
0, -0.579047, 0, 0, 0.520109,-99)    );
  // itree = 108
  fBoostWeights.push_back(0.0950953);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 1,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.514086,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.326974,-99) , 
0, 1.81467, 1, 0, 0.489614,-99) , 
0, 2.02649, 0, 0, 0.503365,-99)    );
  // itree = 109
  fBoostWeights.push_back(0.160671);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 1,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.469963,-99) , 
0, 1.90699, 1, 0, 0.602646,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.543085,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.372971,-99) , 
0, 1.07647, 1, 0, 0.499093,-99) , 
0, 1.25155, 0, 0, 0.517656,-99)    );
  // itree = 110
  fBoostWeights.push_back(0.172383);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 1,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.472445,-99) , 
0, 1.90727, 1, 0, 0.592402,-99) , 
NN(
0, 
0, 
-1, 0.0278007, 0, -1, 0.424579,-99) , 
0, 1.25155, 0, 0, 0.452549,-99)    );
  // itree = 111
  fBoostWeights.push_back(0.126529);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 1.91771, 1, 1, 0.634294,-99) , 
NN(
0, 
0, 
-1, 1.08543, 1, -1, 0.451063,-99) , 
0, 1.26065, 0, 0, 0.481099,-99)    );
  // itree = 112
  fBoostWeights.push_back(0.126981);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 1,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.531873,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.299769,-99) , 
0, -1.15719, 0, 0, 0.506463,-99) , 
0, 2.02543, 0, 0, 0.520562,-99)    );
  // itree = 113
  fBoostWeights.push_back(0.194712);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 1,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.484723,-99) , 
0, 0.0663231, 0, 0, 0.565273,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 1,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.421373,-99) , 
0, 2.00437, 0, 0, 0.450817,-99) , 
0, 0.329182, 1, 0, 0.500633,-99)    );
  // itree = 114
  fBoostWeights.push_back(0.114776);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, -1.11921, 0, 1, 0.65995,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.528705,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.355915,-99) , 
0, -0.505929, 0, 0, 0.505493,-99) , 
0, -0.812991, 1, 0, 0.522752,-99)    );
  // itree = 115
  fBoostWeights.push_back(0.151837);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 1,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.485943,-99) , 
0, 1.91771, 1, 0, 0.610988,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 1,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.448508,-99) , 
0, -1.19231, 1, 0, 0.465143,-99) , 
0, 1.26065, 0, 0, 0.487526,-99)    );
  // itree = 116
  fBoostWeights.push_back(0.171842);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, -0.0154561, 1, 1, 0.557052,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.627548,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.285599,-99) , 
0, -0.758869, 1, 0, 0.457754,-99) , 
0, -0.583598, 0, 0, 0.532553,-99)    );
  // itree = 117
  fBoostWeights.push_back(0.159361);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 1,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.476812,-99) , 
0, 1.91771, 1, 0, 0.600655,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.628578,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.443629,-99) , 
0, -0.666657, 1, 0, 0.475375,-99) , 
0, 1.26065, 0, 0, 0.494455,-99)    );
  // itree = 118
  fBoostWeights.push_back(0.1228);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, -0.105321, 1, 1, 0.547012,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.552693,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.317677,-99) , 
0, -1.16137, 0, 0, 0.459109,-99) , 
0, -0.538877, 0, 0, 0.525409,-99)    );
  // itree = 119
  fBoostWeights.push_back(0.159619);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 1,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.484847,-99) , 
0, -1.11685, 0, 0, 0.637961,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.594728,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.45148,-99) , 
0, 0.402007, 0, 0, 0.515906,-99) , 
0, -0.812065, 1, 0, 0.529252,-99)    );
  // itree = 120
  fBoostWeights.push_back(0.131847);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, -0.0154561, 1, 1, 0.555273,-99) , 
NN(
0, 
0, 
-1, -0.758869, 1, -1, 0.406152,-99) , 
0, -0.583598, 0, 0, 0.515568,-99)    );
  // itree = 121
  fBoostWeights.push_back(0.145847);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, -0.531917, 0, 1, 0.634941,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.508479,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.190925,-99) , 
0, 0.0384127, 0, 0, 0.464001,-99) , 
0, -0.0850052, 1, 0, 0.508233,-99)    );
  // itree = 122
  fBoostWeights.push_back(0.195399);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0.421999, 0, 1, 0.559724,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.871547,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.369798,-99) , 
0, 1.96033, 0, 0, 0.426671,-99) , 
0, 1.09065, 1, 0, 0.509742,-99)    );
  // itree = 123
  fBoostWeights.push_back(0.172621);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 1,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.465921,-99) , 
0, 1.0907, 1, 0, 0.530594,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.51509,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.258944,-99) , 
0, 0.254609, 1, 0, 0.439201,-99) , 
0, 0.388774, 0, 0, 0.476207,-99)    );
  // itree = 124
  fBoostWeights.push_back(0.152194);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 1,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.49656,-99) , 
0, 1.08832, 1, 0, 0.561076,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.524591,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.366328,-99) , 
0, -0.0185923, 1, 0, 0.442464,-99) , 
0, 0.38398, 0, 0, 0.490183,-99)    );
  // itree = 125
  fBoostWeights.push_back(0.122614);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 1,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.47256,-99) , 
0, 1.0907, 1, 0, 0.530071,-99) , 
NN(
0, 
0, 
-1, 0.25401, 1, -1, 0.452269,-99) , 
0, 0.388774, 0, 0, 0.485323,-99)    );
  // itree = 126
  fBoostWeights.push_back(0.117554);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 1,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.491826,-99) , 
0, -0.0154561, 1, 0, 0.525404,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.54931,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.303978,-99) , 
0, -0.758631, 1, 0, 0.432815,-99) , 
0, -0.583598, 0, 0, 0.504313,-99)    );
  // itree = 127
  fBoostWeights.push_back(0.156479);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 1.3259, 0, 1, 0.569995,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.375634,-99) , 
0, 1.95054, 1, 0, 0.542783,-99)    );
  // itree = 128
  fBoostWeights.push_back(0.0859985);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 1,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.483502,-99) , 
0, -0.735438, 1, 0, 0.499663,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.362787,-99) , 
0, -1.06162, 0, 0, 0.485057,-99)    );
  // itree = 129
  fBoostWeights.push_back(0.160986);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 1,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.483775,-99) , 
0, 0.0663231, 0, 0, 0.567127,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 1,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.458229,-99) , 
0, 2.00437, 0, 0, 0.490023,-99) , 
0, 0.329182, 1, 0, 0.523485,-99)    );
  // itree = 130
  fBoostWeights.push_back(0.118032);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 1,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.529459,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.309503,-99) , 
0, -1.14869, 0, 0, 0.506009,-99) , 
0, 2.02649, 0, 0, 0.51921,-99)    );
  // itree = 131
  fBoostWeights.push_back(0.135833);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, -0.117625, 1, 1, 0.528156,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.559006,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.157231,-99) , 
0, -0.644059, 1, 0, 0.390572,-99) , 
0, -0.55399, 0, 0, 0.492022,-99)    );
  // itree = 132
  fBoostWeights.push_back(0.20342);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0.330392, 1, 1, 0.580001,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.536801,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.190071,-99) , 
0, -0.0100979, 1, 0, 0.420926,-99) , 
0, 0.11084, 0, 0, 0.512739,-99)    );
  // itree = 133
  fBoostWeights.push_back(0.109303);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 1,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.489982,-99) , 
0, 1.32358, 0, 0, 0.51697,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.335983,-99) , 
0, 1.94947, 1, 0, 0.49084,-99)    );
  // itree = 134
  fBoostWeights.push_back(0.0729936);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 1,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.489327,-99) , 
0, -0.71444, 1, 0, 0.504858,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.378667,-99) , 
0, -1.04238, 0, 0, 0.490527,-99)    );
  // itree = 135
  fBoostWeights.push_back(0.103764);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 1,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.494099,-99) , 
0, -0.112146, 1, 0, 0.51738,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.561369,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.299808,-99) , 
0, -0.725453, 1, 0, 0.437027,-99) , 
0, -0.547066, 0, 0, 0.498613,-99)    );
  // itree = 136
  fBoostWeights.push_back(0.136784);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, -0.117625, 1, 1, 0.549305,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.531282,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.253466,-99) , 
0, -1.17956, 0, 0, 0.413499,-99) , 
0, -0.55399, 0, 0, 0.514696,-99)    );
  // itree = 137
  fBoostWeights.push_back(0.0732385);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 1,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.493088,-99) , 
0, -0.679999, 1, 0, 0.511601,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.377768,-99) , 
0, -1.01499, 0, 0, 0.495601,-99)    );
  // itree = 138
  fBoostWeights.push_back(0.075655);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 1,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.497725,-99) , 
0, -0.717549, 1, 0, 0.513265,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.32783,-99) , 
0, -1.04696, 0, 0, 0.489161,-99)    );
  // itree = 139
  fBoostWeights.push_back(0.118122);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, -0.0344053, 1, 1, 0.548201,-99) , 
NN(
0, 
0, 
-1, -0.771531, 1, -1, 0.407041,-99) , 
0, -0.598063, 0, 0, 0.514813,-99)    );
  // itree = 140
  fBoostWeights.push_back(0.191641);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, -0.0154561, 1, 1, 0.565587,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 1,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.354146,-99) , 
0, -1.19596, 1, 0, 0.425665,-99) , 
0, -0.583598, 0, 0, 0.531536,-99)    );
  // itree = 141
  fBoostWeights.push_back(0.155632);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 1,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.493361,-99) , 
0, 1.94048, 1, 0, 0.663083,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.525639,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.394646,-99) , 
0, 0.363363, 1, 0, 0.469688,-99) , 
0, 1.23351, 0, 0, 0.499854,-99)    );
  // itree = 142
  fBoostWeights.push_back(0.164225);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 1,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.487694,-99) , 
0, 1.08832, 1, 0, 0.545115,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.536392,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.35732,-99) , 
0, -0.0185923, 1, 0, 0.44234,-99) , 
0, 0.38398, 0, 0, 0.486442,-99)    );
  // itree = 143
  fBoostWeights.push_back(0.155228);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 1.90699, 1, 1, 0.631165,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.563049,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.432095,-99) , 
0, 0.377431, 0, 0, 0.472161,-99) , 
0, 1.25155, 0, 0, 0.498136,-99)    );
  // itree = 144
  fBoostWeights.push_back(0.159799);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 1.09083, 1, 1, 0.568525,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.559005,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.354381,-99) , 
0, 0.254609, 1, 0, 0.492512,-99) , 
0, 0.388774, 0, 0, 0.524851,-99)    );
  // itree = 145
  fBoostWeights.push_back(0.100183);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 1,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.488863,-99) , 
0, -0.0150248, 1, 0, 0.518491,-99) , 
NN(
0, 
0, 
-1, -0.762468, 1, -1, 0.41571,-99) , 
0, -0.585971, 0, 0, 0.494524,-99)    );
  // itree = 146
  fBoostWeights.push_back(0.190611);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0.318647, 1, 1, 0.55068,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.681322,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.3481,-99) , 
0, -0.623835, 1, 0, 0.468534,-99) , 
0, 0.0992561, 0, 0, 0.518743,-99)    );
  // itree = 147
  fBoostWeights.push_back(0.20655);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.716422,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.47539,-99) , 
0, 0.0116299, 0, 0, 0.571735,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.807778,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.426241,-99) , 
0, 1.96515, 0, 0, 0.473209,-99) , 
0, 0.98843, 1, 0, 0.529613,-99)    );
  // itree = 148
  fBoostWeights.push_back(0.119158);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 1.91771, 1, 1, 0.61476,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.534505,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.415635,-99) , 
0, 1.08543, 1, 0, 0.5009,-99) , 
0, 1.26065, 0, 0, 0.519311,-99)    );
  // itree = 149
  fBoostWeights.push_back(0.060509);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, -0.687786, 1, 1, 0.524971,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.427283,-99) , 
0, -1.02298, 0, 0, 0.514236,-99)    );
  // itree = 150
  fBoostWeights.push_back(0.0959395);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 1.3259, 0, 1, 0.541569,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.408007,-99) , 
0, 1.95054, 1, 0, 0.525003,-99)    );
  // itree = 151
  fBoostWeights.push_back(0.170035);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 1,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.490127,-99) , 
0, 1.08841, 1, 0, 0.537267,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.566837,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.362668,-99) , 
0, -0.0185923, 1, 0, 0.454276,-99) , 
0, 0.38398, 0, 0, 0.489588,-99)    );
  // itree = 152
  fBoostWeights.push_back(0.0846619);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, -0.112378, 1, 1, 0.525748,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.527081,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.317844,-99) , 
0, -0.725453, 1, 0, 0.433935,-99) , 
0, -0.547066, 0, 0, 0.504242,-99)    );
  // itree = 153
  fBoostWeights.push_back(0.151909);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 1,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.414992,-99) , 
0, 1.93933, 1, 0, 0.573563,-99) , 
NN(
0, 
0, 
-1, 0.358894, 1, -1, 0.450745,-99) , 
0, 1.23085, 0, 0, 0.472387,-99)    );
  // itree = 154
  fBoostWeights.push_back(0.142643);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 1,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.530597,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.248868,-99) , 
0, -1.15719, 0, 0, 0.494122,-99) , 
0, 2.02543, 0, 0, 0.507539,-99)    );
  // itree = 155
  fBoostWeights.push_back(0.0933644);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.584785,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.481627,-99) , 
0, -0.0591219, 1, 0, 0.500477,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.342786,-99) , 
0, -1.04696, 0, 0, 0.480515,-99)    );
  // itree = 156
  fBoostWeights.push_back(0.145858);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 1,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.471295,-99) , 
0, 1.0967, 1, 0, 0.519733,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.527959,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.388836,-99) , 
0, -0.0031873, 1, 0, 0.452947,-99) , 
0, 0.396709, 0, 0, 0.481793,-99)    );
  // itree = 157
  fBoostWeights.push_back(0.11564);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 1.0907, 1, 1, 0.551697,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.512954,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.396191,-99) , 
0, -0.0127265, 1, 0, 0.449867,-99) , 
0, 0.388774, 0, 0, 0.493955,-99)    );
  // itree = 158
  fBoostWeights.push_back(0.112633);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, -0.0270398, 1, 1, 0.529414,-99) , 
NN(
0, 
0, 
-1, -1.11457, 0, -1, 0.361572,-99) , 
0, -0.592618, 0, 0, 0.488359,-99)    );
  // itree = 159
  fBoostWeights.push_back(0.109615);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 1,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.491633,-99) , 
0, 1.32627, 0, 0, 0.515432,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.323629,-99) , 
0, 1.95054, 1, 0, 0.484733,-99)    );
  // itree = 160
  fBoostWeights.push_back(0.117836);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 1.3169, 0, 1, 0.548996,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.391089,-99) , 
0, 1.93973, 1, 0, 0.523561,-99)    );
  // itree = 161
  fBoostWeights.push_back(0.100025);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 1,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.490776,-99) , 
0, -1.20077, 1, 0, 0.621547,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.515448,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.322313,-99) , 
0, -0.509113, 0, 0, 0.485897,-99) , 
0, -0.816466, 1, 0, 0.49957,-99)    );
  // itree = 162
  fBoostWeights.push_back(0.142399);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 1,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.537446,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.423712,-99) , 
0, 0.333043, 1, 0, 0.475252,-99) , 
0, 2.02649, 0, 0, 0.489564,-99)    );
  // itree = 163
  fBoostWeights.push_back(0.100082);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, -0.0206773, 1, 1, 0.526208,-99) , 
NN(
0, 
0, 
-1, -0.765766, 1, -1, 0.378754,-99) , 
0, -0.590522, 0, 0, 0.489488,-99)    );
  // itree = 164
  fBoostWeights.push_back(0.127749);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 1,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.410074,-99) , 
0, -1.17938, 0, 0, 0.604082,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 1,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.470081,-99) , 
0, -0.631627, 1, 0, 0.486019,-99) , 
0, -0.788483, 1, 0, 0.498739,-99)    );
  // itree = 165
  fBoostWeights.push_back(0.100186);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.986973,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.499999,-99) , 
0, 1.97246, 0, 0, 0.614693,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 1,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.479048,-99) , 
0, -1.19228, 1, 0, 0.496118,-99) , 
0, 1.26065, 0, 0, 0.51629,-99)    );
  // itree = 166
  fBoostWeights.push_back(0.0794642);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 1,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.49711,-99) , 
0, 1.3169, 0, 0, 0.517345,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.363313,-99) , 
0, 1.93973, 1, 0, 0.494664,-99)    );
  // itree = 167
  fBoostWeights.push_back(0.159437);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 1.09111, 1, 1, 0.602845,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.548545,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.405425,-99) , 
0, 0.254624, 1, 0, 0.503705,-99) , 
0, 0.388774, 0, 0, 0.543688,-99)    );
  // itree = 168
  fBoostWeights.push_back(0.108763);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 1,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.481684,-99) , 
0, 1.99205, 0, 0, 0.591025,-99) , 
NN(
0, 
0, 
-1, -1.17946, 0, -1, 0.456805,-99) , 
0, 1.32195, 0, 0, 0.475999,-99)    );
  // itree = 169
  fBoostWeights.push_back(0.128524);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, -0.0344053, 1, 1, 0.552788,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.578656,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.36393,-99) , 
0, -0.771531, 1, 0, 0.481871,-99) , 
0, -0.598063, 0, 0, 0.537546,-99)    );
  // itree = 170
  fBoostWeights.push_back(0.112087);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, -0.0270398, 1, 1, 0.530371,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.576547,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.30698,-99) , 
0, -0.766714, 1, 0, 0.430096,-99) , 
0, -0.592618, 0, 0, 0.507066,-99)    );
  // itree = 171
  fBoostWeights.push_back(0.135366);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 1.09111, 1, 1, 0.552656,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.575592,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.419612,-99) , 
0, -0.0127129, 1, 0, 0.489719,-99) , 
0, 0.388774, 0, 0, 0.516688,-99)    );
  // itree = 172
  fBoostWeights.push_back(0.0912416);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 1,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.490756,-99) , 
0, -0.714414, 1, 0, 0.505063,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.311668,-99) , 
0, -1.04238, 0, 0, 0.478782,-99)    );
  // itree = 173
  fBoostWeights.push_back(0.156347);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0.422091, 0, 1, 0.565563,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.674513,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.419018,-99) , 
0, 1.95968, 0, 0, 0.45559,-99) , 
0, 1.09065, 1, 0, 0.51983,-99)    );
  // itree = 174
  fBoostWeights.push_back(0.0995708);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 1,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.480719,-99) , 
0, -0.140911, 1, 0, 0.498423,-99) , 
NN(
0, 
0, 
-1, -0.73872, 1, -1, 0.406243,-99) , 
0, -0.564767, 0, 0, 0.476283,-99)    );
  // itree = 175
  fBoostWeights.push_back(0.0785864);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 1.99319, 0, 1, 0.526175,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.361792,-99) , 
0, -1.01499, 0, 0, 0.507046,-99)    );
  // itree = 176
  fBoostWeights.push_back(0.109797);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 1,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.489538,-99) , 
0, 1.08841, 1, 0, 0.530175,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.51331,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.428356,-99) , 
0, -0.688408, 1, 0, 0.447387,-99) , 
0, 0.38398, 0, 0, 0.482674,-99)    );
  // itree = 177
  fBoostWeights.push_back(0.18088);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.575438,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.471959,-99) , 
0, 1.0847, 1, 0, 0.525307,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 1,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.16411,-99) , 
0, -1.18302, 1, 0, 0.353746,-99) , 
0, -1.05037, 0, 0, 0.505516,-99)    );
  // itree = 178
  fBoostWeights.push_back(0.118905);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 1.0907, 1, 1, 0.558346,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.573735,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.451033,-99) , 
0, -0.0127129, 1, 0, 0.505073,-99) , 
0, 0.388774, 0, 0, 0.52951,-99)    );
  // itree = 179
  fBoostWeights.push_back(0.106423);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, -0.0321715, 1, 1, 0.541148,-99) , 
NN(
0, 
0, 
-1, -1.12265, 0, -1, 0.405481,-99) , 
0, -0.599543, 0, 0, 0.510993,-99)    );
  // itree = 180
  fBoostWeights.push_back(0.0883422);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, -0.0150248, 1, 1, 0.526179,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.522229,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.315772,-99) , 
0, -0.761663, 1, 0, 0.418952,-99) , 
0, -0.585971, 0, 0, 0.501311,-99)    );
  // itree = 181
  fBoostWeights.push_back(0.136202);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 1.09113, 1, 1, 0.55631,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.555654,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.417809,-99) , 
0, -0.681512, 1, 0, 0.448251,-99) , 
0, 0.388774, 0, 0, 0.494926,-99)    );
  // itree = 182
  fBoostWeights.push_back(0.155386);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.699312,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.476599,-99) , 
0, 1.19075, 0, 0, 0.497321,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 1,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.293128,-99) , 
0, 1.99323, 0, 0, 0.408794,-99) , 
0, 1.79253, 1, 0, 0.481964,-99)    );
  // itree = 183
  fBoostWeights.push_back(0.0793568);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 1,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.498007,-99) , 
0, 1.32586, 0, 0, 0.520398,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.361083,-99) , 
0, 1.95054, 1, 0, 0.499025,-99)    );
  // itree = 184
  fBoostWeights.push_back(0.121136);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.581649,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.484475,-99) , 
0, 1.08781, 1, 0, 0.535322,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.363499,-99) , 
0, -1.04238, 0, 0, 0.515134,-99)    );
  // itree = 185
  fBoostWeights.push_back(0.158141);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.576521,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.420611,-99) , 
0, 0.0418152, 0, 0, 0.551146,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.519501,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.336933,-99) , 
0, -1.15787, 0, 0, 0.438472,-99) , 
0, -0.535604, 0, 0, 0.525281,-99)    );
  // itree = 186
  fBoostWeights.push_back(0.0755708);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 1,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.495995,-99) , 
0, -0.118481, 1, 0, 0.513254,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.530906,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.337928,-99) , 
0, -0.733005, 1, 0, 0.437922,-99) , 
0, -0.55399, 0, 0, 0.496023,-99)    );
  // itree = 187
  fBoostWeights.push_back(0.176851);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.653996,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.464861,-99) , 
0, 0.322087, 1, 0, 0.510176,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.537041,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.175269,-99) , 
0, -0.636332, 1, 0, 0.384404,-99) , 
0, -0.547066, 0, 0, 0.478472,-99)    );
  // itree = 188
  fBoostWeights.push_back(0.121913);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 1,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.49193,-99) , 
0, 1.93756, 1, 0, 0.602302,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.724219,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.471451,-99) , 
0, 1.14616, 0, 0, 0.499823,-99) , 
0, 1.32461, 0, 0, 0.51596,-99)    );
  // itree = 189
  fBoostWeights.push_back(0.0866019);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 1.09111, 1, 1, 0.551122,-99) , 
NN(
0, 
0, 
-1, -1.08207, 0, -1, 0.462663,-99) , 
0, 0.388774, 0, 0, 0.500242,-99)    );
  // itree = 190
  fBoostWeights.push_back(0.192345);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, -0.112476, 1, 1, 0.564532,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.63107,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.230883,-99) , 
0, -0.636332, 1, 0, 0.460155,-99) , 
0, -0.547066, 0, 0, 0.539188,-99)    );
  // itree = 191
  fBoostWeights.push_back(0.0705824);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 1,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.498975,-99) , 
0, 1.30153, 0, 0, 0.514353,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.366901,-99) , 
0, 1.91957, 1, 0, 0.490494,-99)    );
  // itree = 192
  fBoostWeights.push_back(0.122201);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, -0.531917, 0, 1, 0.592164,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.523783,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.27393,-99) , 
0, 0.0389839, 0, 0, 0.48941,-99) , 
0, -0.0850052, 1, 0, 0.512686,-99)    );
  // itree = 193
  fBoostWeights.push_back(0.156983);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, -0.621103, 1, 1, 0.544092,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.867695,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.279435,-99) , 
0, 1.95927, 0, 0, 0.453701,-99) , 
0, 1.79094, 1, 0, 0.530224,-99)    );
  // itree = 194
  fBoostWeights.push_back(0.213354);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 1,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.455451,-99) , 
0, 0.0650937, 0, 0, 0.540124,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 1,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.422856,-99) , 
0, 1.98467, 0, 0, 0.450999,-99) , 
0, 0.326114, 1, 0, 0.488078,-99)    );
  // itree = 195
  fBoostWeights.push_back(0.215519);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, -0.070823, 1, 1, 0.568176,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 1,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.186327,-99) , 
0, -1.18173, 1, 0, 0.375769,-99) , 
0, -1.04915, 0, 0, 0.542902,-99)    );
  // itree = 196
  fBoostWeights.push_back(0.0804659);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.580119,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.494,-99) , 
0, 0.27532, 1, 0, 0.522239,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.38437,-99) , 
0, -1.03897, 0, 0, 0.506337,-99)    );
  // itree = 197
  fBoostWeights.push_back(0.0810634);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 1,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.494624,-99) , 
0, -0.0334028, 1, 0, 0.51838,-99) , 
NN(
0, 
0, 
-1, -0.771531, 1, -1, 0.421,-99) , 
0, -0.598063, 0, 0, 0.495537,-99)    );
  // itree = 198
  fBoostWeights.push_back(0.0984727);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 1,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.421334,-99) , 
0, -1.17109, 0, 0, 0.595256,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 1,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.483333,-99) , 
0, -0.624933, 1, 0, 0.499197,-99) , 
0, -0.781026, 1, 0, 0.508909,-99)    );
  // itree = 199
  fBoostWeights.push_back(0.136549);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0.058901, 0, 1, 0.583555,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 1,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.461301,-99) , 
0, 1.9837, 0, 0, 0.483879,-99) , 
0, 0.320445, 1, 0, 0.522235,-99)    );
   return;
};

// Clean up
inline void ReadBDT::Clear() 
{
   for (unsigned int itree=0; itree<fForest.size(); itree++) { 
      delete fForest[itree]; 
   }
}

inline double ReadBDT::GetMvaValue( const std::vector<double>& inputValues ) const
{
   // classifier response value
   double retval = 0;

   // classifier response, sanity check first
   if (!IsStatusClean()) {
      std::cout << "Problem in class \"" << fClassName << "\": cannot return classifier response"
                << " because status is dirty" << std::endl;
   }
   else {
         retval = GetMvaValue__( inputValues );
   }

   return retval;
}
